name: .NET

on: push

jobs:
    build:
  
      runs-on: self-hosted
  
      steps:
      - name: Delete WeatherSvc Directory
        run: |
          if [ -d "coverage" ]; then
            sudo rm -rf coverage
          fi   
          
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install .NET SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-7.0
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      # Add coverlet.collector nuget package to test project - 'dotnet add <TestProject.cspoj> package coverlet
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
