name: CI/CD Pipeline

on: push

env:
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/weather_svc_image

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t weathersvctestdocker -f Dockerfile .

    - name: Run tests in Docker
      run: docker run --name weathersvc-test-container weathersvctestdocker

    - name: Copy coverage report from Docker to host
      run: |
        mkdir -p ${{ github.workspace }}/coverage
        docker cp weathersvc-test-container:/app/tests/TestResults/ ${{ github.workspace }}/coverage

    - name: Upload coverage report as artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ${{ github.workspace }}/coverage

  build_and_publish:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the WeatherSvcApi Docker image
      run: |
        cd WeatherSvcApi
        docker build -t ${{ env.IMAGE_NAME }} -f Dockerfile .

    - name: Push the Docker image to Docker Hub
      run: docker push ${{ env.IMAGE_NAME }}

  